data1=input("data1:")
data2=input("data2:")
list1=data1.split(",")
list2=data2.split(",")
print("list1:",list1)
print("list2:",list2)
dict(zip(list1,list2))
print("dictionary:",sorted(mydict.items()))
